### ISSUE TITLE
Filter execution probelm

### ISSUE THREAD

**Issue by cmarkello** [BD2KGenomics/brca#154]
Filters on both the Default and Research facing sides of the website are properly querying the server for data, but are not updating what is shown on the website until another interaction that changes a state variable is made.

This causes a lag were when a filter is made, only the results of the previous filter is shown. Afterwards, when you click on a hide/show button, the website then displays the correctly filtered dataset.

This is likely an issue with how the React component lifecycle functions were implemented in the DataTable component.

**Comment by cmarkello** [comment]
More specifically it's an issue with how the `shouldComponentUpdate` function was implemented.

**Comment by benedictpaten** [comment]
Is this fixed?

**Comment by melissacline** [comment]
Moving to brca-website

**Comment by melissacline** [comment]
This issue was moved to BD2KGenomics/brca-website#104

**Comment by cmarkello** [comment]
Yes the filter issue is fixed now, I just double checked the website.
