### ISSUE TITLE
Remap UMD to hg19 and collapse samples for a variant into single vcf rows

### ISSUE THREAD

**Issue by MollyZhang** [BD2KGenomics/brca#23]

**Comment by maximilianh** [comment]
I've added a script vcfMerge to the repo that does this. Note that my google reflexes are bad, there are already scripts out there that do almost the same thing, see 
https://www.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_variantutils_CombineVariants.php

http://vcftools.sourceforge.net/htslib.html#merge
http://vcftools.sourceforge.net/perl_module.html#vcf-merge

**Comment by melissacline** [comment]
That's great - Jing will be really happy to hear this!
