### ISSUE TITLE
Re-scrape UMD to include the biological significance field

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca#29]

**Comment by maximilianh** [comment]
I cannot see this field in the mutation details pages.
http://www.umd.be/BRCA1/4DACTION/WV/200

this will require a bigger change to the scraper. It has to merge data from the big mutation list into the individual details pages. I don't have time right now to do this.

**Comment by melissacline** [comment]
Fair enough, Max.  We can move this to the Futures pile.

**Comment by cmarkello** [comment]
In looking at the big mutation list there is sample specific biological
significance information on the pull-down menu when clicking on the '#
records button'.

...After looking at the html source, I can now see where your parsing
difficulties come from. Although all of the sample information is on the
source page. Simply searching for '---' in the html source will give you
the sample specific data in the large format. The biological significance
data is 2 <td> tags away from the <td> tag containing the '---'+sample_id
for each sample.

**Comment by maximilianh** [comment]
Had 11 hours on the plane, more than enough for this and other things. Done and committed. I did it differently than your suggestion, parsed the tables and rows properly and adding now all fields from the big index file at the end of the .tsv file, which might lead to duplicated info, but at least we're sure now to have everything they show anywhere.

**Comment by melissacline** [comment]
Sweet!  Max, you should come over more often, at least so you have more
plane rides home!

**Comment by cmarkello** [comment]
Were exactly are the parsed tables located? I can't seem to find them in
'/hive/groups/cgl/brca/phase1/data/umdHtml'
