### ISSUE TITLE
Determine if UMD has disease as well as age of onset

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca#30]

**Comment by melissacline** [comment]
Molly and Charlie noticed that the web-scraped version of UMD contains age of onset in the metadata, but no indication of what the onset was.  Is this field somewhere in the online data?  If so, how hard would it be to scrape it?

**Comment by maximilianh** [comment]
To find out if it's in the online data, one can google for UMD and look at any mutation details page:
http://www.umd.be/BRCA1/4DACTION/WV/1
It is not in the online data. I imagine that the disease is usually "breast cancer". Which diseases do the other databases report?
