### ISSUE TITLE
Normalize LOVD data

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca#33]

**Comment by melissacline** [comment]
This will include dealing with the fact that some repositories (such as LOVD) can have multiple VCF rows per variant, as these rows come from different samples, but it's possible that different rows with the same variant will have different metadata.

**Comment by maximilianh** [comment]
see my previous email about this issue. It applies to all database and can
be easily fixed by running all our VCFs through a vcf merging tool.

**Comment by melissacline** [comment]
See Max's tool vcfMerge.

From Max:
I tried to do the other tools do, basically you create a new INFO field (I called it "Desc") and stuff all existing info fields into this one. Within this new field, the old fields are separated by pipe delimiters and the old rows by commas. It works because VCF is semicolon delimited. 
Angie (CC'ed) told me that this schema has become a de facto standard (started by the VEP?) over the last few years and she is also using this in genome browser to format meta data tables on the details pages (you can see this in action e.g. in the Exac track, the CSQ field and DP_HIST fields.

e.g. 
http://genome.ucsc.edu/cgi-bin/hgc?hgsid=428778217_Riq7rUX5kik1yjqBpeASTLriePTO&c=chr1&o=99127253&t=99127254&g=exacVariants&i=G%2FA
